# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JMApp_debug' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JMApp_debug


  target 'JMApp_debugTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JMApp_debug-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JMApp_debug-tvOS

  target 'JMApp_debug-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
